# Generated by Django 5.2.1 on 2025-05-26 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
